version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  docker: circleci/docker@1.4.0  
  kubernetes: circleci/kubernetes

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: danielweiskopf/eksTest
          tag: "latest,$CIRCLE_SHA1"
      - docker/push:
          digest-path: /tmp/digest.txt
          image: danielweiskopf/eksTest
          tag: "latest,$CIRCLE_SHA1"
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
            echo "hello world!!!"
  test:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run: python3 test.py

workflows:
  build_and_test:
    jobs:
      - build-and-push
      - test:
          requires:
            - build-and-push
