version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  docker: circleci/docker@1.4.0  
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: danielweiskopf/ekstest
          tag: "latest,$CIRCLE_SHA1"
      - docker/push:
          digest-path: /tmp/digest.txt
          image: danielweiskopf/ekstest
          tag: "latest,$CIRCLE_SHA1"
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
            echo "hello world!!!"
  test:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run: python3 test.py
  create-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name: 
        description: |
          cluster created by circleci
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
          name: Test cluster



workflows:
  build_and_test:
    jobs:
      - build-and-push
      - test:
          requires:
            - build-and-push
  deploy:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: my-eks-demo
      - aws-eks/delete-cluster:
          cluster-name: my-eks-demo
          requires:
            - create-cluster
