version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  docker: circleci/docker@1.4.0  
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  create-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name: 
        description: |
          cluster created by circleci
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
          name: Test cluster



workflows:
  deploy:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: my-eks-demo
      - aws-eks/delete-cluster:
          cluster-name: my-eks-demo
          requires:
            - aws-eks/create-cluster
